// src/pages/index.tsx
import FirewallForm from "../components/FirewallForm";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">pan-os-typescript</span> App
          </h1>
          <FirewallForm />
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://www.npmjs.com/package/pan-os-typescript"
              target="_blank"
            >
              <h3 className="text-lg font-bold">npm →</h3>
              <div className="text-base">
                Package repository.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://cdot65.github.io/pan-os-typescript/"
              target="_blank"
            >
              <h3 className="text-lg font-bold">Documentation →</h3>
              <div className="text-base">
                Learn more about <span>pan-os-typescript</span>, the libraries it uses, and how
                to integrate it.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}